services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install --upgrade yt-dlp
    startCommand: python deploy.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-downloader-db
          property: connectionString
      - key: FLASK_ENV
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"

databases:
  - name: youtube-downloader-db
    plan: free
    databaseName: youtube_downloader
