services:
  - type: web
    name: youtube-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: youtube-downloader-db
          property: connectionString

databases:
  - name: youtube-downloader-db
    plan: free
    databaseName: youtube_downloader
